LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets
  Enabled: true

BracesAroundHashParameters:
  # Valid values are: braces, no_braces
  EnforcedStyle: no_braces
  Enabled: false

EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: false

SpaceInsideBrackets:
  Description: 'No spaces after [ or before ].'
  Enabled: false

SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  Enabled: true

SpaceInsideHashLiteralBraces:
  Description: "Use spaces inside hash literal braces - or don't."
  # Valid values (for both parameters) are: space, no_space
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  Enabled: false

StringLiterals:
  # Valid values (denoting the preferred quote delimiters) are:
  # single_quotes, double_quotes
  EnforcedStyle: single_quotes
  Enabled: false

#---------------------------------------------------------------------------------------------------
Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise
