global:
  pid_file: /tmp/superloops.pid
  loops_root: <%= Loops.root.to_s %>
  colorful_logs: true
  logger: logs/loops.log

loops:
  simple:
    logger: logs/loops/simple.log
    log_level: error

  complex:
    logger: logs/loops/complex.log
