# STOMP queue server polling loop
queue_loop:
  type: queue
  workers_number: 10

  url: 127.0.0.1
  port: 61613
#  user: guest
#  password: guest

# Simple loop
time_loop:
  type: simple
  
# This loop has no class file so it should not be started
not_a_loop:
  type: simple
