seo_loop:
  type: queue
  workers_number: 2
  poll_period: 1

  server: 127.0.0.1
  user: scribd
  password: scribd
  vhost: /scribd/loops

time_loop:
  type: simple
  disabled: true
  
# This loop has no class file so it should not be started
not_a_loop:
  type: simple
